/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dmx */

#ifndef _Included_Dmx
#define _Included_Dmx
#ifdef __cplusplus
extern "C" {
#endif
#undef Dmx_RESPONSE_OK
#define Dmx_RESPONSE_OK 1L
#undef Dmx_RESPONSE_OPEN_ERROR
#define Dmx_RESPONSE_OPEN_ERROR 2L
#undef Dmx_RESPONSE_SET_CHARACTERISTICS_ERROR
#define Dmx_RESPONSE_SET_CHARACTERISTICS_ERROR 3L
#undef Dmx_RESPONSE_SET_BAUD_RATE_ERROR
#define Dmx_RESPONSE_SET_BAUD_RATE_ERROR 4L
/*
 * Class:     Dmx
 * Method:    setupNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Dmx_setupNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Dmx
 * Method:    sendNaitive
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_Dmx_sendNaitive
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     Dmx
 * Method:    closeNaitive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Dmx_closeNaitive
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
